import http from "node:http";
const REGISTRY_URL="https://raw.githubusercontent.com/b03la013-max/keibametrics-runtime/main/mapping/jra_base_index_mapping_registry_v0.1_20260920.json";
const BASE=["HPI","SSI","CFI","RFI","BVI","JTI","CSI","TRI","BWI","GCI","PRI","KGI","VMI"];
const DERIVED=["DCR","TPI","ZAI_WIN","ZAI_PLACE","SRI","F3S","T3I"];
let registry=null;
async function loadRegistry(){ if(registry) return registry; const r=await fetch(REGISTRY_URL,{cache:"no-store"}); if(!r.ok) throw new Error("REGISTRY_FETCH_"+r.status); registry=await r.json(); return registry; }
function send(res,status,obj){const s=JSON.stringify(obj);res.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":Buffer.byteLength(s)});res.end(s);}
function canonicalItem(index,c){if(!(c&&Number.isFinite(c.value)&&c.rule_id&&c.mapping_version))return null;return{index_name:index,required:true,terminal_status:"CALCULATED",formal_value:c.value,transport_value:c.value,missing_flag:false,calculation_rule_id:c.rule_id,mapping_version:c.mapping_version,evidence_refs:Array.isArray(c.evidence_refs)?c.evidence_refs:[],source_fact:c.source_fact??null,adjustments:c.adjustments??[]};}
function holdItem(index,reason){return{index_name:index,required:true,terminal_status:"RULED-HOLD",formal_value:null,transport_value:50,missing_flag:true,calculation_rule_id:"JRA-UNKNOWN-NEUTRAL-50-v1",mapping_version:"JRA-BASE-INDEX-MAPPING-REGISTRY-v0.1-20260920",hold_reason:reason||"CANONICAL_NUMERIC_MAPPING_UNAVAILABLE",semantics:"transport-neutral only; not ability/probability/weakness"};}
function naItem(index,reason){return{index_name:index,required:true,terminal_status:"NOT-APPLICABLE",formal_value:null,transport_value:50,missing_flag:true,calculation_rule_id:"JRA-NOT-APPLICABLE-v1",mapping_version:"JRA-BASE-INDEX-MAPPING-REGISTRY-v0.1-20260920",hold_reason:reason||"CANON_DECLARED_NOT_APPLICABLE"};}
const POS=["gate","dash_position_acquisition","workout_capability","distance_fit","pedigree_physical","jockey_tactical_fit","sustain_reserve","body_condition_growth","stable_trainer_state","course_fit"];
function positiveGroups(e){if(!e||typeof e!=="object")return[];return POS.filter(k=>{const v=e[k];return v===true||v==="POSITIVE"||v==="STRONG"||(v&&typeof v==="object"&&["POSITIVE","STRONG"].includes(v.status));});}
function calcRunner(r){const cc=r.canonical_components||{};const na=new Set(r.not_applicable_indices||[]);const items=[];for(const idx of [...BASE,...DERIVED]){if(na.has(idx)){items.push(naItem(idx));continue;}const c=canonicalItem(idx,cc[idx]);items.push(c||holdItem(idx,r.newcomer?"NEWCOMER_OR_MAPPING_UNAVAILABLE":"CANONICAL_NUMERIC_MAPPING_UNAVAILABLE"));}const groups=positiveGroups(r.raw_evidence);return{runner_id:String(r.runner_id??r.horse_no),name:r.name||"",newcomer:!!r.newcomer,raw_evidence:r.raw_evidence||{},evidence_groups:groups,winner_reaudit_trigger:groups.length>=2,items};}
async function body(req){let s="";for await(const c of req)s+=c;if(s.length>2_000_000)throw new Error("PAYLOAD_TOO_LARGE");return s?JSON.parse(s):{};}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://localhost");if(req.method==="GET"&&u.pathname==="/health"){const reg=await loadRegistry();return send(res,200,{status:"READY",service:"JRA_BASE_INDEX_CALCULATOR",version:"0.1.0",registry_id:reg.registry_id,mode:"CANONICAL_REPLAY_OR_RULED_HOLD",no_pseudo_precision:true});}
if(req.method==="GET"&&u.pathname==="/registry")return send(res,200,await loadRegistry());
if(req.method==="POST"&&u.pathname==="/calculate-jra-base"){const p=await body(req);if(!p.race_id||!Array.isArray(p.runners)||!p.runners.length)return send(res,422,{status:"FAIL",errors:["RACE_OR_RUNNERS_MISSING"]});const reg=await loadRegistry();const runners=p.runners.map(calcRunner);const all=runners.flatMap(x=>x.items);const allowed=new Set(["CALCULATED","RULED-HOLD","NOT-APPLICABLE"]);const unresolved=all.filter(x=>!allowed.has(x.terminal_status)).length;return send(res,200,{status:unresolved===0?"PASS":"FAIL",race_id:p.race_id,registry_id:reg.registry_id,required_count:all.length,calculated_count:all.filter(x=>x.terminal_status==="CALCULATED").length,ruled_hold_count:all.filter(x=>x.terminal_status==="RULED-HOLD").length,not_applicable_count:all.filter(x=>x.terminal_status==="NOT-APPLICABLE").length,unresolved_count:unresolved,transport_semantics:"RULED-HOLD uses neutral 50 + missing flag for parameter_map-JRA transport only",runners});}
return send(res,404,{status:"NOT_FOUND"});}catch(e){return send(res,500,{status:"FAIL",errors:[String(e?.message||e)]});}});
server.listen(Number(process.env.PORT||3000),"0.0.0.0",()=>console.log("KM_JRA_BASE_INDEX_RUNTIME_READY",process.env.PORT||3000));
