const MAP_URL="https://raw.githubusercontent.com/b03la013-max/keibametrics-runtime/repair/jra-production-mapping-20260921-r1/mapping/jra_base_index_evidence_mapping_v1.0_20260921.json";
const BASE=["HPI","SSI","CFI","RFI","BVI","JTI","CSI","TRI","BWI","GCI","PRI","KGI","VMI"];
const DERIVED=["DCR","TPI","ZAI_WIN","ZAI_PLACE","SRI","F3S","T3I"];
let MAP=null;
async function map(){if(MAP)return MAP;const r=await fetch(MAP_URL,{cache:"no-store"});if(!r.ok)throw new Error("MAP_FETCH_"+r.status);MAP=await r.json();return MAP;}
function js(b,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}})}
function prof(r){let n=r.career_starts;if(n==null)n=r.newcomer?0:4;n=Number(n);return n<=0?"NEWCOMER":n<=3?"LOW_CAREER":"ESTABLISHED"}
function fs(name,f,m){const x=f?.[name];if(!x)return null;const cat=String(x.category||"").toUpperCase();if(!(cat in m.category_scale))throw new Error("BAD_CAT:"+name+":"+cat);if(!Array.isArray(x.evidence_refs)||!x.evidence_refs.length||!x.source_fact||!x.rule_id)throw new Error("BAD_FEATURE:"+name);return {score:Number(m.category_scale[cat]),cat,refs:x.evidence_refs.map(String),fact:String(x.source_fact),rule:String(x.rule_id)}}
function idx(name,p,f,m){const w=m.index_profiles[p][name];let num=0,cov=0,refs=[],facts=[],components=[];for(const [k,ww0] of Object.entries(w)){const z=fs(k,f,m);if(!z)continue;const ww=Number(ww0);num+=z.score*ww;cov+=ww;refs.push(...z.refs);facts.push(k+"="+z.cat+":"+z.fact);components.push({feature:k,weight:ww,category:z.cat,category_score:z.score,feature_rule_id:z.rule,evidence_refs:z.refs,source_fact:z.fact})}const min=Number(m.profiles[p].minimum_index_coverage_weight);if(cov+1e-12<min)throw new Error("LOW_COVERAGE:"+p+":"+name+":"+cov.toFixed(3)+"<"+min);return {value:+(num/cov).toFixed(6),rule_id:"JRA-PROD-EVIDENCE-"+p+"-"+name+"-v1.0",mapping_version:m.mapping_id,evidence_refs:[...new Set(refs)].sort(),source_fact:facts.join(" | "),adjustments:[],coverage_weight:+cov.toFixed(6),profile:p}}
function dcr(r,p,f,m){let out={},sum=0;const ex=r.dcr_inputs||{};for(const [name,s] of Object.entries(m.dcr)){let pts=null,refs=[],fact="",rule="";if(ex[name]){pts=Number(ex[name].points);refs=ex[name].evidence_refs||[];fact=ex[name].source_fact||"";rule=ex[name].rule_id||""}else{let z=s.feature?fs(s.feature,f,m):null;if(!z&&p==="NEWCOMER"&&s.newcomer_fallback_feature)z=fs(s.newcomer_fallback_feature,f,m);if(z){pts=Number(s.max_points)*z.score/100;refs=z.refs;fact=z.fact;rule=z.rule}else if(p==="NEWCOMER"&&s.newcomer_default_points!=null){pts=Number(s.newcomer_default_points);refs=[String(r.runner_id)+":NEWCOMER_STATUS"];fact="No realized pre-race history; uncertainty retained.";rule="JRA-DCR-NEWCOMER-NO-HISTORY-v1"}else throw new Error("DCR_UNRESOLVED:"+r.runner_id+":"+name)}if(!(pts>=0&&pts<=Number(s.max_points))||!refs.length||!fact||!rule)throw new Error("BAD_DCR:"+r.runner_id+":"+name);out[name]={points:+pts.toFixed(6),evidence_refs:refs.map(String),source_fact:String(fact),rule_id:String(rule)};sum+=pts}return {score:+sum.toFixed(6),components:out}}
function derive(base,d,sc){const v={};for(const k of BASE)v[k]=base[k].value;const factor=.70+.30*d.score/100;const major=["HPI","SSI","CFI","RFI","TRI","PRI"].map(k=>v[k]).sort((a,b)=>a-b);const weak=.40*Math.max(0,60-major[0])+.20*Math.max(0,65-major[1]);const tb=v.HPI*.15+v.SSI*.14+v.CFI*.10+v.RFI*.10+v.BVI*.05+v.JTI*.06+v.CSI*.05+v.TRI*.07+v.BWI*.06+v.GCI*.08+v.PRI*.08+v.KGI*.06;const tpi=50+(tb-weak-50)*factor;const zw=v.HPI*.20+v.SSI*.17+v.CFI*.10+v.RFI*.08+v.JTI*.05+v.CSI*.05+v.TRI*.05+v.BWI*.05+v.GCI*.08+v.PRI*.12+v.KGI*.05;const zp=v.HPI*.16+v.SSI*.14+v.CFI*.10+v.RFI*.14+v.JTI*.05+v.CSI*.06+v.TRI*.05+v.BWI*.08+v.GCI*.08+v.PRI*.08+v.KGI*.06;const sri=zp*.45+tpi*.25+v.RFI*.10+v.PRI*.08+v.KGI*.07+v.BWI*.05;const f3=zw*.30+zp*.25+tpi*.25+sri*.15+sc*.05;const t3=zp*.35+tpi*.20+v.RFI*.15+v.PRI*.10+v.GCI*.08+v.CFI*.07+v.VMI*.05;return {DCR:d.score,TPI:tpi,ZAI_WIN:zw,ZAI_PLACE:zp,SRI:sri,F3S:f3,T3I:t3}}
function runner(r,m){const p=prof(r),f=r.evidence_features;if(!f||typeof f!=="object")throw new Error("FEATURES_MISSING:"+r.runner_id);const base={};for(const k of BASE)base[k]=idx(k,p,f,m);const dd=dcr(r,p,f,m);let sc=0;for(const [k,w] of Object.entries(m.scenario_fit))sc+=base[k].value*Number(w);const dv=derive(base,dd,sc),refs=[...new Set(Object.values(base).flatMap(x=>x.evidence_refs))].sort();const canon={...base};for(const k of DERIVED)canon[k]={value:+dv[k].toFixed(6),rule_id:"JRA-"+k+"-v1.0",mapping_version:"index_formula_registry JRA v1.0",evidence_refs:refs,source_fact:"fixed formula replay from production base-index mapping",adjustments:[]};return {runner_id:String(r.runner_id),name:r.name||"",profile:p,canonical_components:canon,dcr:dd,scenario_fit:+sc.toFixed(6)}}
Bun.serve({port:Number(process.env.PORT||3000),async fetch(req){const u=new URL(req.url);try{const m=await map();if(req.method==="GET"&&u.pathname==="/health")return js({status:"READY",service:"JRA_BASE_INDEX_CALCULATOR",mapping_id:m.mapping_id,mode:"PRODUCTION_EVIDENCE_TO_20_INDEX",calibration_status:m.calibration_status});if(req.method==="GET"&&u.pathname==="/registry")return js(m);
if(req.method==="GET"&&u.pathname==="/selftest"){const keys=new Set();for(const p of Object.values(m.index_profiles))for(const w of Object.values(p))for(const k of Object.keys(w))keys.add(k);for(const d of Object.values(m.dcr)){if(d.feature)keys.add(d.feature);if(d.newcomer_fallback_feature)keys.add(d.newcomer_fallback_feature)}const feats=(tag,cat)=>Object.fromEntries([...keys].map(k=>[k,{category:cat,evidence_refs:[tag+":"+k],source_fact:"pre-race "+k,rule_id:"SELFTEST-"+k+"-v1"}]));const rs=[{runner_id:"1",name:"EST",career_starts:12,evidence_features:feats("E","STRONG"),dcr_inputs:{official_recent:{points:23,evidence_refs:["E:r"],source_fact:"12 starts",rule_id:"DCR-E-R"},same_course_distance:{points:18,evidence_refs:["E:c"],source_fact:"course history",rule_id:"DCR-E-C"}}},{runner_id:"2",name:"LOW",career_starts:2,evidence_features:feats("L","POSITIVE"),dcr_inputs:{official_recent:{points:15,evidence_refs:["L:r"],source_fact:"2 starts",rule_id:"DCR-L-R"},same_course_distance:{points:8,evidence_refs:["L:c"],source_fact:"limited course history",rule_id:"DCR-L-C"}}},{runner_id:"3",name:"NEW",career_starts:0,newcomer:true,evidence_features:feats("N","NEUTRAL")}].map(r=>runner(r,m));const required=rs.length*20;return js({status:"PASS",mapping_id:m.mapping_id,profiles:rs.map(x=>x.profile),required_count:required,calculated_count:required,ruled_hold_count:0,not_applicable_count:0,unresolved_count:0})}if(req.method==="POST"&&u.pathname==="/calculate-jra-base"){const p=await req.json();if(!p.race_id||!Array.isArray(p.runners)||p.runners.length<2)return js({status:"FAIL",errors:["RACE_OR_RUNNERS_MISSING"]},422);const rr=p.runners.map(r=>runner(r,m));const required=rr.length*20;return js({status:"PASS",race_id:p.race_id,mapping_id:m.mapping_id,required_count:required,calculated_count:required,ruled_hold_count:0,not_applicable_count:0,unresolved_count:0,runners:rr})}return js({status:"NOT_FOUND"},404)}catch(e){return js({status:"FAIL",errors:[String(e?.message||e)]},422)}}});
